import type { Metadata } from "next";

import { beautifulFont } from "./fonts";
import Header from "@/components/sections/header/header";
import Footer from "@/components/sections/footer/footer";

import "./globals.css";
import ThemeProvider from "@/providers/theme-provider";
import OverlaysCombain from "@/components/overlays/overlays-combain";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='ru'
      className={beautifulFont.className}
      suppressHydrationWarning
    >
      <body className='text-accent bg-accent dark:text-white'>
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
          <OverlaysCombain />
        </ThemeProvider>
      </body>
    </html>
  );
}
